[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  HUGO_VERSION = "0.101.0"  # 统一管理版本
  NODE_VERSION = "16"       # 新增Node版本锁定

[build]
  command = """
    yarn install && 
    yarn --cwd site/netlify/functions/get-categories install &&
    hugo --gc --minify
  """
  publish = "public"  # 修正发布目录
  functions = "site/netlify/functions"  # 对齐实际路径

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[dev]
  framework = "hugo"
  targetPort = 3000
  command = "hugo server -D -E -F --port 3000 --bind 0.0.0.0"

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
    configFile = "cypress/config/project-config.json"

# 静态资源缓存规则 (新增)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
