baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Sotech"
#disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.jpg"]

[taxonomies]
  category = "categories"