backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img"
public_folder: "/img"

collections:
  # ================= 产品集合 =================
  - name: "post"
    label: "产品"
    folder: "site/content/post"
    path: "{{slug}}/index"
    create: true
    media_folder: "../../../static/img"
    public_folder: "/img"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "分类", name: "categories", widget: "categories" } # 使用自定义 widget
      - { label: "简介", name: "description", widget: "text" }
      - { label: "图片", name: "image", widget: "image", required: false }
      - { label: "内容", name: "body", widget: "markdown" }
  # ================= 博客集合 ================= 
  - name: "product_blog"
    label: "博客"
    folder: "site/content/products"
    path: "{{slug}}/index"
    media_folder: "../../../static/img"
    public_folder: "/img"
    create: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "简介", name: "description", widget: "text" }
      - { label: "封面图片", name: "image", widget: "image", required: false }
      - { label: "类型", name: "type", widget: "hidden", default: "product" }
      - { label: "内容", name: "body", widget: "markdown" }

  # ================= 分类配置（已修正） =================
  - name: "categories"
    label: "产品分类"
    files:
      - file: "site/content/categories/_index.md"
        label: "产品分类页面"
        name: "categories_config"
        fields:
          - {label: "页面标题", name: "title", widget: "string"}
          - {label: "顶部背景图", name: "image", widget: "image"}
          - {label: "产品简介", name: "product_intro", widget: "string"}
          - label: "分类列表"
            name: "categories"
            widget: "list"
            fields:
              - {label: "分类名称", name: "name", widget: "string"}
              - {label: "分类图片", name: "image", widget: "image"}
              - {label: "分类描述", name: "description", widget: "text"}
  # ================= 页面配置 =================
  - name: "pages"
    label: "页面"
    files:
      - file: "site/content/_index.md"
        label: "主页"
        name: "主页"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "副标题", name: "subtitle", widget: "string" }
          - { label: "图片", name: "image", widget: "image" }
          - { label: "简介区块", name: "blurb", widget: "object", 
              fields: [
                { label: "标题", name: "heading", widget: "string" },
                { label: "内容", name: "text", widget: "markdown" }
              ] 
            }
          - { label: "价值观", name: "values", widget: "object", 
              fields: [
                { label: "标题", name: "heading", widget: "string" },
                { label: "内容", name: "text", widget: "markdown" }
              ] 
            }
          - { label: "介绍", name: "intro", widget: "object", 
              fields: [
                { label: "标题", name: "heading", widget: "string" },
                { label: "内容", name: "text", widget: "text" }
              ] 
            }
          - { label: "产品列表", name: "products", widget: "list", 
              fields: [
                { label: "图片", name: "image", widget: "image" },
                { label: "描述", name: "text", widget: "text" }
              ] 
            }

      - file: "site/content/contact/_index.md"
        label: "联系我们"
        name: "联系我们"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "内容", name: "body", widget: "markdown" }
          - label: "联系方式"
            name: "contact_entries"
            widget: "list"
            fields:
              - label: "标题"
                name: "heading"
                widget: "string"
              - label: "内容"
                name: "text"
                widget: "text"

  # ================= 网站设置 =================
  - name: "site_settings"
    label: "网站设置"
    files:
      - file: "site/data/footer.json"
        label: "页脚"
        name: "页脚"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "简介", name: "blurb", widget: "text" }
      - file: "site/hugo.toml"
        label: "Hugo配置"
        name: "配置"
        editor:
          preview: false
        fields:
          - { label: "浏览器标签标题", name: "title", widget: "string" }
          - label: "参数"
            name: "params"
            widget: "object"
            fields:
              - label: "Open Graph图片"
                name: "images"
                widget: "list"
                field: { label: "图片", name: "image", widget: "image" }

scripts:
  - ../../../static/admin/js/category-widget.js
