backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img"
public_folder: "/img"

collections:
  # =============== 产品集合 ===============
  - name: "post"
    label: "产品"
    folder: "site/content/post"
    create: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - label: "分类"
        name: "categories"
        widget: "select"
        multiple: true  # 允许多选
        options: "/.netlify/functions/get-categories"  # 指向分类接口
        default: ["battery-components"]
      - { label: "简介", name: "description", widget: "text" }
      - { label: "产品图片", name: "image", widget: "image" }
      - { label: "详细内容", name: "body", widget: "markdown" }

  # =============== 分类管理 ===============
  - name: "categories"
    label: "产品分类"
    files:
      - file: "site/content/categories/_index.md"
        label: "分类配置"
        fields:
          - { label: "页面标题", name: "title", widget: "string" }
          - { label: "顶部图片", name: "image", widget: "image" }
          - { label: "产品总述", name: "product_intro", widget: "text" }
          - label: "分类列表"
            name: "categories"  # 必须与Markdown中的字段名一致
            widget: "list"
            fields:
              - { label: "分类名称", name: "name", widget: "string" }
              - { label: "URL标识符", name: "slug", widget: "string", 
                  pattern: ["^[a-z0-9-]+$", "只能包含小写字母、数字和连字符"] }
              - { label: "分类图片", name: "image", widget: "image" }
              - { label: "详细描述", name: "description", widget: "text" }

  # =============== 其他集合保持原样 ===============
  - name: "product_blog"
    label: "博客"
    folder: "site/content/products"
    # ... 其他字段保持不变 ...

  - name: "pages"
    label: "页面"
    files:
      # ... 原有页面配置保持不变 ... 

  - name: "site_settings"
    label: "网站设置"
    files:
      # ... 原有配置保持不变 ...
