backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img"
public_folder: "/img"

collections:
  # ================ 产品集合 ================
  - name: "products"
    label: "产品管理"
    folder: "site/content/products"
    create: true
    fields:
      - { label: "产品名称", name: "title", widget: "string" }
      - label: "产品分类"
        name: "categories"
        widget: "relation"
        multiple: true
        collection: "product_categories"  # 指向分类集合
        value_field: "slug"
        display_fields: ["name"]
        search_fields: ["name"]
      - { label: "产品简介", name: "description", widget: "text" }
      - { label: "产品图片", name: "image", widget: "image" }
      - { label: "详细参数", name: "body", widget: "markdown" }

  # ================ 分类管理 ================
  - name: "product_categories"
    label: "产品分类"
    folder: "site/content/categories"
    create: true
    identifier_field: "slug"
    fields:
      - { label: "分类名称", name: "name", widget: "string", required: true }
      - { label: "URL标识符", name: "slug", widget: "string", 
          pattern: ["^[a-z0-9-]+$", "只允许小写字母、数字和连字符"] }
      - { label: "分类图片", name: "image", widget: "image" }
      - { label: "分类描述", name: "description", widget: "text" }

  # ================ 博客管理 ================
  - name: "blogs"
    label: "技术博客"
    folder: "site/content/blogs"
    create: true
    fields:
      - { label: "文章标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "摘要", name: "excerpt", widget: "text" }
      - { label: "封面图片", name: "image", widget: "image" }
      - { label: "正文内容", name: "body", widget: "markdown" }

  # ================ 页面管理 ================
  - name: "pages"
    label: "页面配置"
    files:
      - file: "site/content/_index.md"
        label: "首页配置"
        name: "home_config"  # 唯一标识
        fields:
          - { label: "主标题", name: "title", widget: "string" }
          - { label: "副标题", name: "subtitle", widget: "string" }
          - { label: "背景图", name: "hero_image", widget: "image" }

      - file: "site/content/contact.md"
        label: "联系我们"
        name: "contact_page"  # 唯一标识
        fields:
          - { label: "页面标题", name: "title", widget: "string" }
          - { label: "联系方式", name: "contacts", widget: "list",
              fields: [
                { label: "类型", name: "type", widget: "string" },
                { label: "信息", name: "value", widget: "string" }
              ] }

  # ================ 网站设置 ================
  - name: "settings"
    label: "全局设置"
    files:
      - file: "site/config/site.json"
        label: "基础配置"
        name: "site_settings"  # 唯一标识
        fields:
          - { label: "网站标题", name: "title", widget: "string" }
          - { label: "SEO描述", name: "description", widget: "text" }

      - file: "site/config/footer.json"
        label: "页脚配置"
        name: "footer_settings"  # 唯一标识
        fields:
          - { label: "版权信息", name: "copyright", widget: "string" }
          - { label: "备案号", name: "icp", widget: "string" }
