backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "产品" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    media_folder: "../../../static/img" # 显式设置媒体文件夹路径
    public_folder: "/img" # 显式设置公共路径
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "分类", name: "categories", widget: "categories", multiple: true}
      - {label: "简介", name: "description", widget: "text"}
      - {label: "图片", name: "image", widget: "image", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
  - name: "product_blog" # 产品博客集合
    label: "博客" # 在 UI 中显示的名称
    folder: "site/content/products" # 存储文档的文件夹路径
    path: "{{slug}}/index" # 每个文档都在以 slug 命名的文件夹中
    media_folder: "../../../static/img"
    public_folder: "/img"
    create: true # 允许用户在此集合中创建新文档
    fields: # 此集合中每个文档的字段
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "简介", name: "description", widget: "text"}
      - {label: "封面图片", name: "image", widget: "image", required: false}
      - {label: "类型", name: "type", widget: "hidden", default: "product"}
      - {label: "内容", name: "body", widget: "markdown"}
  - name: "categories"
    label: "产品分类"
    files:
      - file: "site/content/categories/_index.md"
        label: "产品分类页面"
        name: "categories"
        fields:
          - {label: "页面标题", name: "title", widget: "string"}
          - {label: "顶部背景图", name: "image", widget: "image"}
          - {label: "产品简介", name: "product_intro", widget: "string"}
          - label: "分类列表"
            name: "categories_list"
            widget: "list"
            fields:
              - {label: "分类名称", name: "name", widget: "string"}
              - {label: "分类图片", name: "image", widget: "image"}
              - {label: "分类描述", name: "description", widget: "text"}
  - name: "pages"
    label: "页面"
    files:
      - file: "site/content/_index.md"
        label: "主页"
        name: "主页"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "副标题", name: "subtitle", widget: "string"}
          - {label: "图片", name: "image", widget: "image"}
          - {label: "简介区块", name: "blurb", widget: "object", fields: [
              {label: "标题", name: "heading", widget: "string"},
              {label: "内容", name: "text", widget: "markdown"}]}
          - {label: "价值观", name: "values", widget: "object", fields: [
              {label: "标题", name: "heading", widget: "string"},
              {label: "内容", name: "text", widget: "markdown"}]}
          - {label: "介绍", name: "intro", widget: "object", fields: [
              {label: "标题", name: "heading", widget: "string"},
              {label: "内容", name: "text", widget: "text"}]}
          - {label: "产品列表", name: "products", widget: "list", fields: [
              {label: "图片", name: "image", widget: "image"},
              {label: "描述", name: "text", widget: "text"}]}

      - file: "site/content/contact/_index.md"
        label: "联系我们"
        name: "联系我们"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "内容", name: "body", widget: "markdown"}
          - label: "联系方式"
            name: "contact_entries"
            widget: "list"
            fields:
              - label: "标题"
                name: "heading"
                widget: "string"
              - label: "内容"
                name: "text"
                widget: "text"
      - file: "site/content/blogs/_index.md"
        label: "最新动态"
        name: "产品页面"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "类型", name: "type", widget: "hidden", default: "products"}
          - {label: "封面图片", name: "image", widget: "image"}
          - {label: "简介", name: "description", widget: "text"}
          - {label: "内容", name: "body", widget: "markdown"}
      - file: "site/content/values/_index.md"
        label: "公司简介"
        name: "公司简介"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "图片", name: "image", widget: "image"}
          - label: "价值观"
            name: "values"
            widget: "list"
            fields:
              - {label: "标题", name: "heading", widget: "string"}
              - {label: "内容", name: "text", widget: "markdown"}
              - {label: "图片", name: "imageUrl", widget: "image"}
  - name: "site_settings"
    label: "网站设置"
    files:
      - file: "site/data/footer.json"
        label: "页脚"
        name: "页脚"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "简介", name: "blurb", widget: "text"}
      - file: "site/hugo.toml"
        label: "Hugo配置"
        name: "配置"
        editor:
          preview: false
        fields:
          - {label: "浏览器标签标题", name: "title", widget: "string"}
          - label: "参数"
            name: "params"
            widget: "object"
            fields:
              - label: "Open Graph图片"
                name: "images"
                widget: "list"
                field: { label: "图片", name: "image", widget: "image" }

scripts:
  - /admin/js/category-widget.js
